# -*- coding: utf-8 -*-
"""Inventory Misalignment & Network Intelligence System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1-MNQeWYXhKmeTUYay3DDNowOr0JeAh
"""

import pandas as pd
import numpy as np

# ===============================
# 1️⃣ IMPORT LIBRARIES
# ===============================
import pandas as pd
import numpy as np

# ===============================
# 2️⃣ LOAD DATA (PARQUET ONLY)
# ===============================
df = pd.read_parquet(r"C:\Users\Rudra\Desktop\Inventory Misalignment\train.parquet")   # adjust path if needed

print("Shape:", df.shape)

# ===============================
# 3️⃣ BASIC VALIDATION
# ===============================
df["dt"] = pd.to_datetime(df["dt"])

print("\nMissing values check:")
print(df.isnull().sum())

print("\nType checks:")
print("hours_sale:", type(df["hours_sale"].iloc[0]))
print("hours_stock_status:", type(df["hours_stock_status"].iloc[0]))

# ===============================
# 4️⃣ DAILY OPERATIONAL METRICS
# ===============================

# Total hours
df["total_hours"] = df["hours_stock_status"].apply(len)

# Stockout hours (1 = stockout)
df["stockout_hours"] = df["hours_stock_status"].apply(lambda x: np.sum(x))

# In-stock hours
df["in_stock_hours"] = df["total_hours"] - df["stockout_hours"]

# Basic hourly service rate
df["hourly_service_rate"] = df["in_stock_hours"] / df["total_hours"]

# ===============================
# 5️⃣ DEMAND STRUCTURE METRICS
# ===============================

# Daily total sales (sanity check)
df["calculated_daily_units"] = df["hours_sale"].apply(lambda x: np.sum(x))

# Peak demand
df["peak_hour_sales"] = df["hours_sale"].apply(lambda x: np.max(x))

# Average hourly demand
df["avg_hourly_sales"] = df["hours_sale"].apply(lambda x: np.mean(x))

# Demand concentration ratio
df["sales_variation"] = df["peak_hour_sales"] / (df["avg_hourly_sales"] + 1e-6)

# ===============================
# 6️⃣ DEMAND-WEIGHTED SERVICE LEVEL (MEMORY SAFE)
# ===============================

dws = []

for sales, stock in zip(df["hours_sale"], df["hours_stock_status"]):

    total_sales = sales.sum()

    if total_sales > 0:
        availability = 1 - stock   # 1 = available, since stock column is stockout flag
        dws_value = (sales * availability).sum() / total_sales
        dws.append(dws_value)
    else:
        dws.append(np.nan)

df["demand_weighted_service"] = dws

# ===============================
# 7️⃣ SUMMARY CHECK
# ===============================

print("\nDemand Weighted Service Summary:")
print(df["demand_weighted_service"].describe())

print("\nBasic vs Demand-Weighted Comparison:")
print(df[["hourly_service_rate","demand_weighted_service"]].head())

# ===============================
# 8️⃣ REVENUE AT RISK
# ===============================

# Replace NaN DWS (zero demand days) with 1 for revenue calculation
df["dws_filled"] = df["demand_weighted_service"].fillna(1)

# Revenue lost due to stockouts
df["revenue_at_risk"] = df["sale_amount"] * (1 - df["dws_filled"])

# Summary
print("\nRevenue at Risk Summary:")
print(df["revenue_at_risk"].describe())

# Total revenue impact
total_revenue_lost = df["revenue_at_risk"].sum()

print("\nTotal Revenue at Risk:", total_revenue_lost)

# ===============================
# 9️⃣ SORT FOR ROLLING CALCULATION
# ===============================

df = df.sort_values(["store_id", "product_id", "dt"])
# ===============================
# 🔟 EXPECTED DEMAND (7-day rolling mean)
# ===============================

df["expected_demand_7d"] = (
    df.groupby(["store_id", "product_id"])["calculated_daily_units"]
      .transform(lambda x: x.rolling(7, min_periods=3).mean())
)
# ===============================
# 1️⃣1️⃣ PHANTOM INVENTORY SCORE
# ===============================

df["phantom_score"] = 0.0

condition = (
    (df["hourly_service_rate"] > 0.8) &
    (df["calculated_daily_units"] == 0) &
    (df["expected_demand_7d"] > 0)
)

# Score intensity proportional to expected demand
df.loc[condition, "phantom_score"] = (
    df.loc[condition, "expected_demand_7d"] /
    (df.loc[condition, "expected_demand_7d"].max())
)
print("\nPhantom Score Summary:")
print(df["phantom_score"].describe())

print("\nHigh Risk Phantom Cases:")
print(df[df["phantom_score"] > 0.5][[
    "store_id",
    "product_id",
    "dt",
    "expected_demand_7d",
    "hourly_service_rate"
]].head(10))

df["phantom_flag"] = (df["phantom_score"] > 0.5).astype(int)
store_phantom = (
    df.groupby("store_id")["phantom_flag"]
      .mean()
      .sort_values(ascending=False)
)

print(store_phantom.head(10))
df["phantom_revenue_loss"] = df["revenue_at_risk"] * df["phantom_flag"]

print("Total Phantom Revenue Loss:", df["phantom_revenue_loss"].sum())

df["avg_unit_price"] = df["sale_amount"] / df["calculated_daily_units"]
df["avg_unit_price"] = df["avg_unit_price"].replace([np.inf, -np.inf], np.nan)
df["phantom_revenue_est"] = (
    df["expected_demand_7d"] *
    df["avg_unit_price"].fillna(df["avg_unit_price"].median()) *
    df["phantom_flag"]
)

print("Estimated Phantom Revenue Loss:", df["phantom_revenue_est"].sum())

df = df.sort_values(["store_id", "product_id", "dt"])
# ===============================
# 1️⃣ SHORT & MEDIUM TERM VELOCITY
# ===============================

# 7-day rolling demand
df["velocity_7d"] = (
    df.groupby(["store_id", "product_id"])["calculated_daily_units"]
      .transform(lambda x: x.rolling(7, min_periods=3).mean())
)

# 30-day rolling demand
df["velocity_30d"] = (
    df.groupby(["store_id", "product_id"])["calculated_daily_units"]
      .transform(lambda x: x.rolling(30, min_periods=10).mean())
)
df["velocity_ratio"] = df["velocity_7d"] / (df["velocity_30d"] + 1e-6)
df["velocity_flag"] = "stable"

df.loc[df["velocity_ratio"] < 0.7, "velocity_flag"] = "declining"
df.loc[df["velocity_ratio"] < 0.5, "velocity_flag"] = "high_decline"
df.loc[df["velocity_ratio"] > 1.2, "velocity_flag"] = "accelerating"
print("\nVelocity Ratio Summary:")
print(df["velocity_ratio"].describe())

print("\nVelocity Flag Distribution:")
print(df["velocity_flag"].value_counts())

df["decline_flag"] = df["velocity_flag"].isin(["declining", "high_decline"]).astype(int)

decline_revenue = (df["sale_amount"] * df["decline_flag"]).sum()

print("Revenue exposed to declining SKUs:", decline_revenue)
store_decay = (
    df.groupby("store_id")["decline_flag"]
      .mean()
      .sort_values(ascending=False)
)

print(store_decay.head(10))
category_decay = (
    df.groupby("first_category_id")["decline_flag"]
      .mean()
      .sort_values(ascending=False)
)

print(category_decay.head(10))

# ===============================
# 1️⃣2️⃣-B: SUPPLY CHAIN NERVOUSNESS (BULLWHIP INDEX)
# ===============================

# 1. Calculate Daily Closing Stock (Approximation from hours)
df['daily_closing_stock'] = df['hours_stock_status'].apply(lambda x: len(x) - sum(x))

# 2. Rolling Coefficient of Variation (CV) for Sales (7-day)
# CV = Sigma / Mu
df['sales_rolling_std'] = df.groupby(['store_id', 'product_id'])['calculated_daily_units'].transform(lambda x: x.rolling(7).std())
df['sales_rolling_mean'] = df.groupby(['store_id', 'product_id'])['calculated_daily_units'].transform(lambda x: x.rolling(7).mean())
df['sales_cv'] = df['sales_rolling_std'] / (df['sales_rolling_mean'] + 1e-6)

# 3. Rolling Coefficient of Variation (CV) for Inventory (7-day)
df['stock_rolling_std'] = df.groupby(['store_id', 'product_id'])['daily_closing_stock'].transform(lambda x: x.rolling(7).std())
df['stock_rolling_mean'] = df.groupby(['store_id', 'product_id'])['daily_closing_stock'].transform(lambda x: x.rolling(7).mean())
df['stock_cv'] = df['stock_rolling_std'] / (df['stock_rolling_mean'] + 1e-6)

# 4. Nervousness Index (Inventory Volatility / Demand Volatility)
# High Value (>1.5) = Panic Ordering / Erratic Supply
# Low Value (<0.5) = Passive / Neglect
df['nervousness_index'] = df['stock_cv'] / (df['sales_cv'] + 1e-6)

# 5. Classify the Behavior
df['manager_behavior'] = 'Synchronized'
df.loc[df['nervousness_index'] > 1.5, 'manager_behavior'] = 'Panic/Over-Reactive'
df.loc[df['nervousness_index'] < 0.5, 'manager_behavior'] = 'Passive/Neglect'

print("\nManager Behavior Distribution:")
print(df['manager_behavior'].value_counts())

# ===============================
# MARKDOWN RISK SCORE
# ===============================

df["markdown_risk_score"] = 0

condition = (
    df["velocity_flag"].isin(["declining", "high_decline"]) &
    (df["stock_hour6_22_cnt"] > 10) &   # adjust threshold if needed
    (df["discount"] < df["discount"].median()) &
    (df["activity_flag"] == 0)
)

df.loc[condition, "markdown_risk_score"] = 1

print("Total Markdown Risk Cases:", df["markdown_risk_score"].sum())

# ===============================
# 1️⃣3️⃣-B: SUBSTITUTABILITY & REVENUE MIGRATION
# ===============================

# ===============================
# 1️⃣3️⃣-B: SUBSTITUTABILITY & REVENUE MIGRATION
# ===============================

# 1. Define "Surplus Sales" (Sales significantly above expected)
df['surplus_sales'] = df['calculated_daily_units'] - df['expected_demand_7d']
df['is_surplus'] = (df['surplus_sales'] > 0).astype(int)

# 2. Aggregating at Store-Category-Date Level
cat_group = df.groupby(['store_id', 'second_category_id', 'dt']).agg(
    total_stockout_loss=('revenue_at_risk', 'sum'),
    total_surplus_revenue=('sale_amount', lambda x: x[df.loc[x.index, 'is_surplus'] == 1].sum()),
    stockout_count=('revenue_at_risk', lambda x: (x > 0).sum())
).reset_index()

# 3. Calculate "Captured Revenue" (We assume up to 50% could be substitution)
cat_group['likely_substitution_val'] = cat_group[['total_stockout_loss', 'total_surplus_revenue']].min(axis=1) * 0.5

# 4. Merge back to main DF to adjust Revenue at Risk
df = df.merge(cat_group[['store_id', 'second_category_id', 'dt', 'likely_substitution_val']],
              on=['store_id', 'second_category_id', 'dt'],
              how='left')

# 5. Distribute substitution credit safely

df['net_revenue_at_risk'] = df['revenue_at_risk'].copy()
mask_stockout = df['revenue_at_risk'] > 0

stockout_counts = (
    df[mask_stockout]
    .groupby(['store_id','second_category_id','dt'])
    .size()
    .reset_index(name='stockout_group_count')
)

df = df.merge(
    stockout_counts,
    on=['store_id','second_category_id','dt'],
    how='left'
)

df['stockout_group_count'] = df['stockout_group_count'].fillna(0)

df.loc[mask_stockout, 'net_revenue_at_risk'] -= (
    df.loc[mask_stockout, 'likely_substitution_val'] /
    df.loc[mask_stockout, 'stockout_group_count']
)

df['net_revenue_at_risk'] = df['net_revenue_at_risk'].clip(lower=0)

print(f"Gross Revenue at Risk: {df['revenue_at_risk'].sum():,.2f}")
print(f"Net Revenue at Risk (After Substitution): {df['net_revenue_at_risk'].sum():,.2f}")

markdown_revenue_exposure = df.loc[
    df["markdown_risk_score"] == 1,
    "sale_amount"
].sum()

print("Revenue sitting on markdown risk SKUs:", markdown_revenue_exposure)
store_markdown_risk = (
    df.groupby("store_id")["markdown_risk_score"]
      .sum()
      .sort_values(ascending=False)
)

print(store_markdown_risk.head(10))

# ===============================
# STORE LEVEL RISK COMPONENTS
# ===============================

store_risk = df.groupby("store_id").agg(
    service_risk = ("revenue_at_risk", "sum"),
    decay_risk = ("decline_flag", "mean"),
    markdown_risk = ("markdown_risk_score", "sum"),
    phantom_risk = ("phantom_flag", "mean")
).reset_index()
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

risk_columns = ["service_risk", "decay_risk", "markdown_risk", "phantom_risk"]

store_risk[risk_columns] = scaler.fit_transform(store_risk[risk_columns])
store_risk["composite_risk_index"] = (
    0.35 * store_risk["service_risk"] +
    0.35 * store_risk["decay_risk"] +
    0.20 * store_risk["markdown_risk"] +
    0.10 * store_risk["phantom_risk"]
)
store_risk = store_risk.sort_values("composite_risk_index", ascending=False)

print(store_risk.head(10))
store_risk["risk_tier"] = pd.qcut(
    store_risk["composite_risk_index"],
    q=4,
    labels=["Low", "Moderate", "High", "Critical"]
)

print(store_risk["risk_tier"].value_counts())

store_risk["risk_tier_absolute"] = "Low"

store_risk.loc[store_risk["composite_risk_index"] > 0.45, "risk_tier_absolute"] = "Critical"
store_risk.loc[
    (store_risk["composite_risk_index"] > 0.35) &
    (store_risk["composite_risk_index"] <= 0.45),
    "risk_tier_absolute"
] = "High"
store_risk.loc[
    (store_risk["composite_risk_index"] > 0.25) &
    (store_risk["composite_risk_index"] <= 0.35),
    "risk_tier_absolute"
] = "Moderate"

# ===============================
# 1️⃣6️⃣: NETWORK TRANSSHIPMENT OPTIMIZER (FINAL THRESHOLD = 3.0)
# ===============================

# 1. Define Destinations (Stores Needing Stock)
# Logic: We filter for stores losing > $3.00 per day on this item.
# This represents a "Significant Operational Failure" worth fixing.
destinations = df[
    (df['net_revenue_at_risk'] > 3.0) &       
    (df['dt'] == df['dt'].max())            
][['store_id', 'product_id', 'net_revenue_at_risk', 'dt', 'city_id']].copy() 

# 2. Define Sources (Stores with Excess Stock)
# Logic: Service Rate = 1.0 (Perfectly in stock) AND
# Velocity Flag is NOT 'accelerating' (They don't need it urgently)
sources = df[
    (df['hourly_service_rate'] == 1.0) &
    (~df['velocity_flag'].isin(['accelerating'])) & 
    (df['dt'] == df['dt'].max())
][['store_id', 'product_id', 'dt', 'city_id']].copy()

# 3. Rename columns for merging
destinations = destinations.rename(columns={'store_id': 'to_store', 'net_revenue_at_risk': 'potential_gain'})
sources = sources.rename(columns={'store_id': 'from_store'})

# 4. Create Network Graph (Strict Match on Product & City)
# We strictly match on 'city_id' to ensure transport costs are negligible.
transfers = pd.merge(destinations, sources, on=['product_id', 'city_id', 'dt'])

# 5. Filter Self-Transfers
transfers = transfers[transfers['to_store'] != transfers['from_store']]

# 6. Calculate "Net Opportunity Value"
# Gain ($3+) - Cost ($0.50 local transport)
transfers['transfer_net_value'] = transfers['potential_gain'] - 0.50
transfers = transfers[transfers['transfer_net_value'] > 0].sort_values('transfer_net_value', ascending=False)

print(f"\n🚀 Top Recommended Network Transfers (Threshold > $3.00):")
if transfers.empty:
    print("No transfers found > $3.00. (System is efficient or thresholds are too high).")
else:
    print(transfers[['from_store', 'to_store', 'product_id', 'potential_gain', 'transfer_net_value']].head(10))
    
# ===============================
# 1️⃣7️⃣: COST OF WAIT vs. WASTE FRONTIER (REVISED)
# ===============================

# 1. Costs
df['cost_of_waste'] = (df['daily_closing_stock'] * df['avg_unit_price'] * 0.0005)
df['cost_of_wait'] = df['net_revenue_at_risk'] * 0.30 

# 2. Aggregation
frontier = df.groupby('product_id').agg({
    'hourly_service_rate': 'mean', 
    'cost_of_waste': 'sum',       
    'cost_of_wait': 'sum'          
}).reset_index()

# 3. REVISION: Summation instead of Multiplication
# This represents "Total Economic Friction"
frontier['total_economic_drag'] = frontier['cost_of_waste'] + frontier['cost_of_wait']

print("\n📉 Top Inefficient SKUs (Highest Economic Friction):")
print(frontier.sort_values('total_economic_drag', ascending=False).head(10))


transfers.to_csv("network_transfers.csv", index=False)
store_risk.to_csv("store_risk.csv", index=False)
frontier.to_csv("sku_friction.csv", index=False)
transfers.to_csv("network_transfers.csv", index=False)

summary = pd.DataFrame({
    "Metric": ["Gross Revenue at Risk", "Net Revenue at Risk"],
    "Value": [
        df["revenue_at_risk"].sum(),
        df["net_revenue_at_risk"].sum()
    ]
})